import Head from "next/head";

import styles from "./index.module.scss";
import Hero from "@/components/hero/hero";
import Playlist from "@/components/playlist/playlist";

export default function Home() {
  return (
    <>
      <Head>
        <title>Readingmood</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Hero />
        <Playlist />
      </main>
    </>
  )
}
